[package]
name = "miniscreenshot-wgpu"
version = "0.3.0"
edition = "2021"
description = "wgpu screenshot helper for the miniscreenshot ecosystem. Re-exports wgpu."
authors = ["Markus Mayer <widemeadows@gmail.com>"]
license = "EUPL-1.2 OR MIT OR Apache-2.0"
repository = "https://github.com/sunsided/miniscreenshot"
keywords = ["screenshot", "wgpu", "screenshot-helper"]
categories = ["multimedia::images", "graphics"]
readme = "../README.md"

[features]
default = ["wgpu-29"]
wgpu-28 = ["dep:wgpu_28"]
wgpu-29 = ["dep:wgpu_29"]

[dependencies]
miniscreenshot = { version = "0.3", path = "../miniscreenshot" }
wgpu_28 = { package = "wgpu", version = "28", optional = true }
wgpu_29 = { package = "wgpu", version = "29", optional = true }

[dev-dependencies]
pollster = "0.4"

[package.metadata.docs.rs]
features = ["wgpu-29"]
